### PR TITLE
Version 0.4.5

### LINKED ISSUE #954: [develop] Admin interface does not return user's NodeInfo
Admin interface does not return user's NodeInfo:

Steps:

```
vadym@ubuntu:~/yggdrasil-go$ ./yggdrasilctl getself
Build name:   	yggdrasil-develop                                               	
Build version:	0.4.4-36-g69632ba                                               	
IPv6 address: 	200:8869:4984:2e39:95b:4eb4:d347:cb0c                           	
IPv6 subnet:  	300:8869:4984:2e39::/64                                         	
Coordinates:  	[]                                                              	
Public key:   	bbcb5b3de8e37b5258a5965c1a79dee07dde372e8cc610e9d23e57d4e8828fd2	
vadym@ubuntu:~/yggdrasil-go$ ./yggdrasilctl -json getnodeinfo key=bbcb5b3de8e37b5258a5965c1a79dee07dde372e8cc610e9d23e57d4e8828fd2
{
  "bbcb5b3de8e37b5258a5965c1a79dee07dde372e8cc610e9d23e57d4e8828fd2": {
    "buildarch": "amd64",
    "buildname": "yggdrasil-develop",
    "buildplatform": "linux",
    "buildversion": "0.4.4-36-g69632ba"
  }
}
```

ygg.conf file:

```
  # Your public key. Your peers may ask you for this to put
  # into their AllowedPublicKeys configuration.
  PublicKey: bbcb5b3de8e37b5258a5965c1a79dee07dde372e8cc610e9d23e57d4e8828fd2

  # Your private key. DO NOT share this with anyone!
  PrivateKey: aa19c2ac9a8f388dda3b4b04365e0d110ce6735c088fcdd1e4bce5d7ba61a83dbbcb5b3de8e37b5258a5965c1a79dee07dde372e8cc610e9d23e57d4e8828fd2

  # Local network interface name for TUN adapter, or "auto" to select
  # an interface automatically, or "none" to run without TUN.
  IfName: auto

  # Maximum Transmission Unit (MTU) size for your local TUN interface.
  # Default is the largest supported size for your platform. The lowest
  # possible value is 1280.
  IfMTU: 65535

  # By default, nodeinfo contains some defaults including the platform,
  # architecture and Yggdrasil version. These can help when surveying
  # the network and diagnosing network routing problems. Enabling
  # nodeinfo privacy prevents this, so that only items specified in
  # "NodeInfo" are sent back if specified.
  NodeInfoPrivacy: false

  # Optional node info. This must be a { "key": "value", ... } map
  # or set as null. This is entirely optional but, if set, is visible
  # to the whole network on request.
  NodeInfo: {
	name: Zurich
  }
}
```

### PR DESCRIPTION
**Pull request by neilalexander**
Still to do before release:

- [x] Fix #954 
- [x] Investigate #891
- [ ] ~~Investigate #953~~

### CODE REVIEW

**Comment by neilalexander** [comment]
Release candidate builds: https://nightly.link/yggdrasil-network/yggdrasil-go/actions/runs/3256173796

**Comment by Vort** [comment]
#891 problem is still reproducing as it was before.

**Comment by neilalexander** [comment]
> #891 problem is still reproducing as it was before.

On which version of Windows? I tested it on Server 2019 and can't reproduce it.

**Comment by Vort** [comment]
> On which version of Windows?

On the same as I mentioned in #891 - Windows 7 SP1 x64

**Comment by neilalexander** [comment]
> > On which version of Windows?
> 
> On the same as I mentioned in #891 - Windows 7 SP1 x64

Honestly I don't know what we can do here. I'd need some other people to test it on more recent versions of Windows that are actually in support, as [Windows 7 isn't](https://www.microsoft.com/en-gb/windows/end-of-support).

If we update the Wireguard TUN packages then we will probably break Go 1.17 support and I still don't know if it will fix the problem.

**Comment by Vort** [comment]
I realized that problem is slightly different than I imagined.
(I compare two versions right now: 0.4.0-30-gf92d812 and 0.4.4-41-g6bda57e)
Problem with abrupt exit happens in _both_ versions.
Both versions also leave trash adapter behind.
But in older version it is recreated silently (with 0.11 wintun.dll, driver may be newer).
While in new version (0.14.1 .dll) recreation fails and only new adapter is created (which creates more and more of them with each restart).

**Comment by Vort** [comment]
> Honestly I don't know what we can do here.

Debug prints can be added to code to find where exactly it exits.

> on more recent versions of Windows that are actually in support

It will not fix #891.

> as Windows 7 isn't

OSes do not disappear from existence once support ends.
It is still possible to install them, use and make compatible software for them.

> You can try the attached ZIP which includes the Wireguard dependency update

Same problem happens.

**Comment by neilalexander** [comment]
> Debug prints can be added to code to find where exactly it exits.

There are already `Stopping` and `Stopped` lines in the core router — if those appear in the log, then the TUN adapter has *already been closed*, as `(tun.Device).Close()` from the TUN library has already been called by that point.

> It will not fix #891.

So far I have been unable to reproduce this issue on newer versions of Windows. I don't have a Windows 7 box though, so I would rely on community feedback from other Windows users to understand if the problem is specific to certain versions. Anything is possible in that regard.

> OSes do not disappear from existence once support ends. It is still possible to install them, use and make compatible software for them.

That's true, but there's a limit to what we can reasonably support, especially when we don't own the full supply chain of dependencies. We are only two maintainers doing this entirely in our spare time and we're using libraries written by other people whom we have no control over — if they aren't testing against Windows 7 then the problem probably exists upstream too.

**Comment by neilalexander** [comment]
Updated release candidate builds: https://nightly.link/yggdrasil-network/yggdrasil-go/actions/runs/3256421478

**Comment by Vort** [comment]
> There are already Stopping and Stopped lines in the core router — if those appear in the log

That's the problem - they do not appear in log when I stop service.

**Comment by neilalexander** [comment]
> That's the problem - they do not appear in log when I stop service.

Are you clicking “Stop” or “Restart”? (I don’t know if there is a difference really.)

On Server 2019, they do appear in the log as of today’s builds.

**Comment by Vort** [comment]
> Are you clicking “Stop” or “Restart”?

Stop. From Task Manager by the way. It do not have Restart. But it should not matter.

**Comment by vikulin** [comment]
https://github.com/yggdrasil-network/yggdrasil-go/issues/891 does not reproduce for me: Windows 11, 64bit

**Pull request merged**
