### PR TITLE
Revert downgrading of wireguard and update wintun in windows installer

### PR DESCRIPTION
**Pull request by r4sas**
Related: #862

### CODE REVIEW

**Comment by neilalexander** [comment]
Builds from CI for testing:

* 64-bit: [yggdrasil-develop-0.4.2-0001-x64.zip](https://github.com/yggdrasil-network/yggdrasil-go/files/7523765/yggdrasil-develop-0.4.2-0001-x64.zip) / [yggdrasil-develop-0.4.2-0001-x64.msi](https://ci.appveyor.com/api/buildjobs/clb8l8rgwsq2x9gp/artifacts/yggdrasil-develop-0.4.2-0001-x64.msi)
* 32-bit: [yggdrasil-develop-0.4.2-0001-x86.zip](https://github.com/yggdrasil-network/yggdrasil-go/files/7523766/yggdrasil-develop-0.4.2-0001-x86.zip) / [yggdrasil-develop-0.4.2-0001-x86.msi](https://ci.appveyor.com/api/buildjobs/clb8l8rgwsq2x9gp/artifacts/yggdrasil-develop-0.4.2-0001-x86.msi)

I will await feedback from Windows users before approving for merge.

**Comment by neilalexander** [comment]
Windows Server 2019 Datacenter 1809 (64-bit):
```
2021/11/11 23:26:34 Build name: yggdrasil-develop
2021/11/11 23:26:34 Build version: 0.4.2-1-g87e9361
2021/11/11 23:26:34 Starting up...
2021/11/11 23:26:34 Startup complete
2021/11/11 23:26:34 Starting multicast module
2021/11/11 23:26:34 TCP admin socket listening on 127.0.0.1:9001
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x31941d]

goroutine 38 [running, locked to thread]:
runtime.throw({0x4a7ff5, 0x0})
        C:/go/src/runtime/panic.go:1198 +0x76 fp=0xc0000acd88 sp=0xc0000acd58 pc=0x206116
runtime.sigpanic()
        C:/go/src/runtime/signal_windows.go:260 +0x10c fp=0xc0000acdd0 sp=0xc0000acd88 pc=0x21900c
golang.org/x/sys/windows.UTF16PtrToString(0x0)
        C:/Users/appveyor/go/pkg/mod/golang.org/x/sys@v0.0.0-20210611083646-a4fc73990273/windows/syscall_windows.go:132 +0x1d fp=0xc0000ace18 sp=0xc0000acdd0 pc=0x31941d
golang.zx2c4.com/wireguard/tun/wintun.setupLogger.func1(0x0, 0x0)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210604143328-f9b48a961cd2/tun/wintun/wintun_windows.go:53 +0x1c fp=0xc0000ace60 sp=0xc0000ace18 pc=0x42bd3c
runtime.call16(0x0, 0x4bdd70, 0xc0000acee8, 0x0, 0x0, 0x10, 0xc0000ad140)
        C:/go/src/runtime/asm_amd64.s:625 +0x50 fp=0xc0000ace80 sp=0xc0000ace60 pc=0x231470
runtime.callbackWrap(0x701fbfee30)
        C:/go/src/runtime/syscall_windows.go:378 +0x134 fp=0xc0000ad260 sp=0xc0000ace80 pc=0x2211d4
runtime.cgocallbackg1(0x2210a0, 0xc000080000, 0x0)
        C:/go/src/runtime/cgocall.go:306 +0x29a fp=0xc0000ad330 sp=0xc0000ad260 pc=0x1d43ba
runtime.cgocallbackg(0xc000084680, 0x300000002, 0xc000084680)
        C:/go/src/runtime/cgocall.go:232 +0x106 fp=0xc0000ad3c8 sp=0xc0000ad330 pc=0x1d4046
runtime.cgocallbackg(0x2210a0, 0x701fbfee30, 0x0)
        <autogenerated>:1 +0x36 fp=0xc0000ad3f0 sp=0xc0000ad3c8 pc=0x235236
runtime.cgocallback(0x1d3ecc, 0x234b40, 0xc0000802e0)
        C:/go/src/runtime/asm_amd64.s:915 +0xd7 fp=0xc0000ad418 sp=0xc0000ad3f0 pc=0x233077
runtime.systemstack_switch()
        C:/go/src/runtime/asm_amd64.s:350 fp=0xc0000ad420 sp=0xc0000ad418 pc=0x230f20
runtime.cgocall(0x234b40, 0xc0000802e0)
        C:/go/src/runtime/cgocall.go:166 +0xac fp=0xc0000ad458 sp=0xc0000ad420 pc=0x1d3ecc
syscall.Syscall(0x7ff8a6a03a80, 0x2, 0xc00012e000, 0xc00009e630, 0x0)
        C:/go/src/runtime/syscall_windows.go:479 +0xf4 fp=0xc0000ad490 sp=0xc0000ad458 pc=0x22f9f4
syscall.Syscall(0xc000121890, 0x4be2d8, 0xc0000ad540, 0x235a2b, 0x7ff8c1062970)
        <autogenerated>:1 +0x2b fp=0xc0000ad4e0 sp=0xc0000ad490 pc=0x235a2b
golang.zx2c4.com/wireguard/tun/wintun.(*Pool).OpenAdapter(0xc00012e000, {0xc00000af40, 0x20a50d})
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210604143328-f9b48a961cd2/tun/wintun/wintun_windows.go:89 +0xbc fp=0xc0000ad558 sp=0xc0000ad4e0 pc=0x42b79c
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0xc00000af40, 0x9}, 0x4b5eb8, 0xcf39)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210604143328-f9b48a961cd2/tun/tun_windows.go:75 +0x4d fp=0xc0000ad5d0 sp=0xc0000ad558 pc=0x42c66d
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup.func1()
        C:/projects/yggdrasil-go/src/tuntap/tun_windows.go:34 +0xb1 fp=0xc0000ad770 sp=0xc0000ad5d0 pc=0x432571
golang.zx2c4.com/wireguard/windows/elevate.DoAsSystem(0xc0000adac8)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.3.14/elevate/doas.go:114 +0x622 fp=0xc0000adaa8 sp=0xc0000ad770 pc=0x42e562
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0x4a7edd, {0xc00000af40, 0xc000153ca0}, {0xc0000a0060, 0x2}, 0x0)
        C:/projects/yggdrasil-go/src/tuntap/tun_windows.go:27 +0x15d fp=0xc0000adb68 sp=0xc0000adaa8 pc=0x43245d
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0xc000116540)
        C:/projects/yggdrasil-go/src/tuntap/tun.go:135 +0x2b4 fp=0xc0000adf70 sp=0xc0000adb68 pc=0x431874
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        C:/projects/yggdrasil-go/src/tuntap/tun.go:108 +0x26 fp=0xc0000adf90 sp=0xc0000adf70 pc=0x431586
github.com/Arceliar/phony.Block.func1()
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:80 +0x26 fp=0xc0000adfb0 sp=0xc0000adf90 pc=0x344d06
github.com/Arceliar/phony.(*Inbox).run(0xc000116588)
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:89 +0x34 fp=0xc0000adfc8 sp=0xc0000adfb0 pc=0x344d74
github.com/Arceliar/phony.(*Inbox).restart·dwrap·1()
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:121 +0x26 fp=0xc0000adfe0 sp=0xc0000adfc8 pc=0x344f66
runtime.goexit()
        C:/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000adfe8 sp=0xc0000adfe0 pc=0x2332a1
created by github.com/Arceliar/phony.(*Inbox).restart
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:121 +0x5b

goroutine 1 [select]:
main.main()
        C:/projects/yggdrasil-go/cmd/yggdrasil/main.go:396 +0x2b1

goroutine 6 [syscall]:
os/signal.signal_recv()
        C:/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
        C:/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        C:/go/src/os/signal/signal.go:151 +0x2c

goroutine 7 [chan receive]:
github.com/Arceliar/phony.Block({0x512be0, 0xc000116540}, 0xc00009a030)
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:81 +0xc7
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start(0xc000116540)
        C:/projects/yggdrasil-go/src/tuntap/tun.go:107 +0x94
main.run({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0xc00000a100, 0xe}, ...}, ...)
        C:/projects/yggdrasil-go/cmd/yggdrasil/main.go:360 +0xfba
created by main.main
        C:/projects/yggdrasil-go/cmd/yggdrasil/main.go:395 +0x245

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x1a77d109768, 0x72)
        C:/go/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00003bc48, 0x1dced4, 0x0)
        C:/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc00019e018, 0xc00003bc50)
        C:/go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc00019e000, 0x238, {0xc0001aa000, 0x41, 0x1dced4}, 0x101a757e50a28)
        C:/go/src/internal/poll/fd_windows.go:810 +0x6d
internal/poll.(*FD).Accept(0xc00019e000, 0xc00003be28)
        C:/go/src/internal/poll/fd_windows.go:844 +0x1d6
net.(*netFD).accept(0xc00019e000)
        C:/go/src/net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc000198018)
        C:/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc000198018)
        C:/go/src/net/tcpsock.go:262 +0x3d
github.com/yggdrasil-network/yggdrasil-go/src/admin.(*AdminSocket).listen(0xc000042800)
        C:/projects/yggdrasil-go/src/admin/admin.go:234 +0x938
created by github.com/yggdrasil-network/yggdrasil-go/src/admin.(*AdminSocket).Start
        C:/projects/yggdrasil-go/src/admin/admin.go:156 +0xaf

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x1a77d109850, 0x72)
        C:/go/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00007d418, 0xc000157b00, 0x0)
        C:/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc00007d418, 0x4bdd98)
        C:/go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).ReadFrom(0xc00007d400, {0xc000206000, 0x64, 0x2030000})
        C:/go/src/internal/poll/fd_windows.go:581 +0x155
net.(*netFD).readFrom(0xc00007d400, {0xc000206000, 0x0, 0x6e8660})
        C:/go/src/net/fd_posix.go:62 +0x29
net.(*UDPConn).readFrom(0xc00018a000, {0xc000206000, 0x0, 0x1dced4}, 0xc000202060)
        C:/go/src/net/udpsock_posix.go:47 +0x3e
net.(*UDPConn).readFromUDP(0xc0000061e0, {0xc000206000, 0x800, 0xc00018a000}, 0xc000206000)
        C:/go/src/net/udpsock.go:116 +0x31
net.(*UDPConn).ReadFrom(0x219512, {0xc000206000, 0x800, 0x800})
        C:/go/src/net/udpsock.go:125 +0x50
golang.org/x/net/ipv6.(*payloadHandler).ReadFrom(0x4a7e5f, {0xc000206000, 0x4ab320, 0x10})
        C:/Users/appveyor/go/pkg/mod/golang.org/x/net@v0.0.0-20210610132358-84b48f89b13b/ipv6/payload_nocmsg.go:20 +0x42
github.com/yggdrasil-network/yggdrasil-go/src/multicast.(*Multicast).listen(0xc000044a80)
        C:/projects/yggdrasil-go/src/multicast/multicast.go:349 +0xaf
created by github.com/yggdrasil-network/yggdrasil-go/src/multicast.(*Multicast)._start
        C:/projects/yggdrasil-go/src/multicast/multicast.go:105 +0x285
```

**Comment by r4sas** [comment]
No issues on Windows 10 21H1 (19043.1200).

**Comment by r4sas** [comment]
Looks like appveyor produces broken binaries with go 1.17.2. I have built with go 1.17.3 and everything works with my installer, but didn't works with appveyor's.

**Comment by r4sas** [comment]
> go1.17.3 (released 2021-11-04) includes security fixes to the archive/zip and debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the go command, the misc/wasm directory, and to the net/http and syscall packages. See the Go 1.17.3 milestone on our issue tracker for details.

> runtime.sigpanic()

As you can see...

**Comment by r4sas** [comment]
Please try out installer with ygg built by 1.17.3.

**Comment by neilalexander** [comment]
Problem seems to persist.

**Comment by r4sas** [comment]
Switching to 0.5.1 resolves problem on Windows Server 2019 1804.

**Comment by r4sas** [comment]
Note about https://github.com/yggdrasil-network/yggdrasil-go/pull/865/commits/3d18f5e2667588ad6644ff869653187b4af33abd: as you can see here, PR checked out to develop, so any windows build will be incorrectly builded with current core, not proposed.

**Comment by r4sas** [comment]
Rabased commits to latest `develop` commits.

**Review by neilalexander — APPROVED** [review]
Seems to have fixed installation on my Windows VM too, thanks for this!

**Pull request merged**
