### PR TITLE
Add proxyprotocol support to TLS listener

### PR DESCRIPTION
**Pull request by PufferBlue**
fixes https://github.com/yggdrasil-network/yggdrasil-go/issues/970

### CODE REVIEW

**Comment by PufferBlue** [comment]
Added an option to enable proxyprotocol support for TLS listeners with config like this
```
Listen: [
    tls://127.0.0.1:8443?proxyprotocol=true
]
```
Tested with Nginx as frontend proxy and yggdrasilctl reads real user IPs now
```
stream {
    listen 0.0.0.0:443 reuseport;
    ssl_preread on;
    proxy_pass 127.0.0.1:8443;
    proxy_protocol on;
}
```

**Comment by majestrate** [comment]
LGTM

**Comment by FliKites** [comment]
Will this ever be merged?

**Comment by neilalexander** [comment]
What problem is this solving exactly?

**Comment by FliKites** [comment]
Verify authenticity of Handshake domain names using DANE on the YGGDrasil network with the help of the LetsDane Proxy: https://github.com/buffrr/letsdaneThanks for the commit. Much appreciated.  ---- On Sun, 26 Feb 2023 16:22:23 -0500  ***@***.***  wrote ----
What problem is this solving exactly?

**Comment by neilalexander** [comment]
Closing as this feels like an extreme edge case that I'm not really sure we want to support forever more. I'm also not entirely confident this won't affect TLS peerings in some other way.

**Pull request closed without merging**
