### PR TITLE
Move yggdrasilctl responses to separate functions (small refactoring)

### PR DESCRIPTION
**Pull request by kotovalexarian**
It's always recommended to split code into small units such as functions because this makes it more understandable. Many code linting tools ([RuboCop](https://rubocop.org) for Ruby programming language for example) have metrics which warn about too long functions: Assigment-Branch-Condition size, methods length, etc. Also this opens the opportunity of testing the code in future.

### CODE REVIEW

**Comment by kotovalexarian** [comment]
To be sure that the code haven't beed changed, you can run:

```
git diff 35e8ff7c9d72c9245fc1c6d6b07c1c18e965f0e5..41853a9d793c05331a9962228ea30f4690aa80e9 --ignore-all-space
```

**Comment by cofob** [comment]
Merge to "develop" branch

**Review by cofob — APPROVED** [review]
This looks fine.

**Comment by kotovalexarian** [comment]
@cofob Changed target branch to `develop`. You can review again with
```
git diff b333c7d7f32a5ba0e597788c9b83f8e7b295f827..fa65253e5709d37bb1debea656d826ee34316df9 --ignore-all-space
```

**Comment by kotovalexarian** [comment]
Sorry, I've renamed the branch in my repo and GitHub closed the PR. New PR is #815

**Pull request closed without merging**
