### PR TITLE
Split yggdrasilctl code into separate functions (refactoring)

### PR DESCRIPTION
**Pull request by kotovalexarian**
It's always recommended to split code into small units such as functions because this makes it more understandable. Many code linting tools ([RuboCop](https://rubocop.org) for Ruby programming language for example) have metrics which warn about too long functions: Assigment-Branch-Condition size, methods length, etc. Also this opens the opportunity of testing the code in future.

The previous PR (#814) have been accidentally closed by GitHub when I renamed the branch.

### CODE REVIEW

**Review by neilalexander — CHANGES_REQUESTED** [review]
I absolutely welcome the split to multiple functions but I feel like the `cmd_line_env` package is an unnecessary point of complexity. I'd prefer it if that code could be put back into the `main` package.

**Comment by kotovalexarian** [comment]
> I absolutely welcome the split to multiple functions but I feel like the `cmd_line_env` package is an unnecessary point of complexity. I'd prefer it if that code could be put back into the `main` package.

Ok, I'll change the code to follow this.

**Comment by kotovalexarian** [comment]
@neilalexander done

**Review by neilalexander — APPROVED** [review]

**Comment by neilalexander** [comment]
Thanks for this!

**Pull request merged**
