### PR TITLE
Accept some golint suggestions

### PR DESCRIPTION
**Pull request by yujiri8**
Partial work on #314. I'm new to this project, so I didn't tackle anything that involved adding comments or renaming things. Most of my changes are removing unnecessary `else`s when the `if` ends with a `return`, plus a couple of comment typos.

### CODE REVIEW

**Comment by yujiri8** [comment]
Oh, actually I noticed Klesomik had already made PR #674, which partially overlapped with my changes, so I rebased to put mine on top of theirs.

**Comment by Klesomik** [comment]
Great job! I think it worth adding golang-ci lint in CI and it will save a lot of time in the future.

**Comment by Klesomik** [comment]
And maybe it is better to commit these changes not in master but in a different branch

**Review by neilalexander — APPROVED** [review]

**Comment by neilalexander** [comment]
Thanks for this! I have also added `golangci-lint` into CI under #733 (although it doesn't fail on lint errors yet).

**Pull request merged**
