### PR TITLE
Ported WinTun start code from rivmesh.

### LINKED ISSUE #993: Windows version fails to start
I've found time to debug this one :)

When started from admin command line it shows this error:
```
2022/11/23 00:27:09 Build name: yggdrasil-develop
2022/11/23 00:27:09 Build version: 0.4.7
2022/11/23 00:27:09 TCP admin socket listening on 127.0.0.1:9001
2022/11/23 00:27:09 Connected outbound TCP: blablabla
2022/11/23 00:27:09 Using existing driver 0.14
2022/11/23 00:27:09 Creating adapter
2022/11/23 00:27:09 Connected outbound TLS: blablabla
2022/11/23 00:27:24 Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022/11/23 00:27:24 Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Cannot create a file when that file already exists. (Code 0x000000B7)
panic: Error creating interface: Cannot create a file when that file already exists.

goroutine 21 [running]:
main.run({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0xc0000bc0c0, 0x27}, ...}, ...)
        /home/revertron/IdeaProjects/yggdrasil-go/cmd/yggdrasil/main.go:365 +0x1585
main.main.func1()
        /home/revertron/IdeaProjects/yggdrasil-go/cmd/yggdrasil/main.go:405 +0x85
created by main.main
        /home/revertron/IdeaProjects/yggdrasil-go/cmd/yggdrasil/main.go:403 +0x1b7
```
But sometimes it just starts instantaneously:
```
2022/11/23 00:31:08 Build name: yggdrasil-develop
2022/11/23 00:31:08 Build version: 0.4.7
2022/11/23 00:31:08 TCP admin socket listening on 127.0.0.1:9001
2022/11/23 00:31:08 Connected outbound TCP: blablabla
2022/11/23 00:31:08 Using existing driver 0.14
2022/11/23 00:31:08 Creating adapter
2022/11/23 00:31:08 Your public key is blablabla
2022/11/23 00:31:08 Your IPv6 address is 200:blablabla
2022/11/23 00:31:08 Your IPv6 subnet is 300:blablabla
2022/11/23 00:31:09 Connected outbound TLS: blablabla
```

### PR DESCRIPTION
**Pull request by Revertron**
Fixes #993.

Also, I've changed go version 1.17 -> 1.18, updated wireguard dependency, and imported wintun module.

This fix has one drawback: the TUN device may appear after 15 seconds. It seems that the cause is somewhere in Wintun code. But the main goal is that TUN interface is created every time, and the service doesn't crash anymore.

### CODE REVIEW

**Comment by Revertron** [comment]
Don't know what is the problem with the Lint. Error is very ambiguous :(

**Comment by mkg20001** [comment]
you're calling a function that returns something, but don't do anything with it

**Comment by neilalexander** [comment]
> Don't know what is the problem with the Lint. Error is very ambiguous :(

Fixed.

**Comment by Revertron** [comment]
BTW, the last commit eliminated the 15 seconds delays, everything is working flawlessly.

**Pull request closed without merging**
