### PR TITLE
Fixed #884

### LINKED ISSUE #884: `-address` and `-subnet` command line switches need descriptive error message if used without `-useconffile`
`-address` and `-subnet` command line swiches not work

yggdrasil 0.4.2, installed as `.deb` on `aarch64` platform.

### PR DESCRIPTION
**Pull request by solanav**
This adds a descriptive error when trying to use -address or -subnet without specifying the config file. Seems to be a common mistake with a very simple fix.

This is the output before:
image

And this is the output after the fix:
image

### CODE REVIEW

**Comment by neilalexander** [comment]
It looks like you've accidentally committed `yggdrasil` and `yggdrasilctl` binaries too, can you fix that?

**Comment by solanav** [comment]
sorry for the late response @neilalexander , the binaries are removed now!

**Comment by majestrate** [comment]
squash those first 2 commits if you can.

**Comment by solanav** [comment]
I tried to squash my commits but I couldn't find a way sorry. Don't know if you can help

**Comment by majestrate** [comment]
> I tried to squash my commits but I couldn't find a way sorry. Don't know if you can help

https://garrytrinder.github.io/2020/03/squashing-commits-using-interactive-rebase is a good overview of doing that.

**Pull request merged**
