### PR TITLE
More docker support

### PR DESCRIPTION
**Pull request by yangm97**

### CODE REVIEW

**Comment by neilalexander** [comment]
Please create PRs against the `develop` branch instead of `master`.

**Comment by yangm97** [comment]
Done.

**Comment by Arceliar** [comment]
Reopening so we can think about what to do here.

Compared to the file under `contrib/docker` (now under `contrib/docker/alpine`, this uses `-autoconf`, which means you get a different IP every time you start it, no clearnet peers, etc... I'm not sure how useful that is as the default docker file. But as I've said, I have almost 0 experience with docker, so I'm not the target audience for this.

**Comment by yangm97** [comment]
@Arceliar the CMD is overridable. When you `docker run` without arguments, it will take the default CMD, but if the user mounts a config file and then adds -useconf... it will run from that instead.

**Comment by yangm97** [comment]
I could add some concrete examples somewhere, maybe?

**Pull request closed without merging**
